var searchData=
[
  ['jacobian_5fjointparams_5fto_5fmodelparams_0',['jacobian_jointparams_to_modelparams',['../namespacemomentum.html#a58976f70181d218f1b771f9756c74a8c',1,'momentum::jacobian_jointParams_to_modelParams(const Eigen::Ref&lt; const Eigen::VectorX&lt; T &gt; &gt; &amp;jacobian_jointParams, const Eigen::Index iJointParam, const ParameterTransform &amp;parameterTransform, Eigen::Ref&lt; Eigen::MatrixX&lt; T &gt; &gt; jacobian)'],['../namespacemomentum.html#ae9c09b4c882dfd3f75e9f627086b0e41',1,'momentum::jacobian_jointParams_to_modelParams(const T &amp;jacobian_jointParams, const Eigen::Index iJointParam, const ParameterTransform &amp;parameterTransform, Eigen::Ref&lt; Eigen::MatrixX&lt; T &gt; &gt; jacobian)'],['../namespacemomentum.html#a3332816b68f46e53f140cc194095ea7a',1,'momentum::jacobian_jointParams_to_modelParams(const T &amp;jacobian_jointParams, const Eigen::Index iJointParam, const ParameterTransform &amp;parameterTransform, Eigen::MatrixBase&lt; Derived &gt; &amp;jacobian)'],['../namespacemomentum.html#a1f9f092de71f3a7ec6835ce10ed5cbe4',1,'momentum::jacobian_jointParams_to_modelParams(const T &amp;jacobian_jointParams, const Eigen::Index iJointParam, const Eigen::Index iRow, const ParameterTransform &amp;parameterTransform, Eigen::Ref&lt; Eigen::MatrixX&lt; T &gt; &gt; jacobian)'],['../namespacemomentum.html#a75f92c9556cc340ba6afd88f1cbf3983',1,'momentum::jacobian_jointParams_to_modelParams(const T jacobian_jointParams, const Eigen::Index iJointParam, const ParameterTransform &amp;parameterTransform, Eigen::Ref&lt; Eigen::MatrixX&lt; T &gt; &gt; jacobian)']]],
  ['jerksequenceerrorfunctiont_1',['jerksequenceerrorfunctiont',['../classmomentum_1_1JerkSequenceErrorFunctionT.html#a2cfaf09ad6e0e8cd4571665f4dd43b15',1,'momentum::JerkSequenceErrorFunctionT::JerkSequenceErrorFunctionT(const Skeleton &amp;skel, const ParameterTransform &amp;pt)'],['../classmomentum_1_1JerkSequenceErrorFunctionT.html#a4bc219e449f2faf70abde406ed8bfd20',1,'momentum::JerkSequenceErrorFunctionT::JerkSequenceErrorFunctionT(const Character &amp;character)']]],
  ['jointerrorfunctiont_2',['jointerrorfunctiont',['../classmomentum_1_1JointErrorFunctionT.html#a4ef9fd30130bfb5cb66146130dbf8f16',1,'momentum::JointErrorFunctionT::JointErrorFunctionT(const Skeleton &amp;skel, const ParameterTransform &amp;pt, const T &amp;lossAlpha=GeneralizedLossT&lt; T &gt;::kL2, const T &amp;lossC=T(1))'],['../classmomentum_1_1JointErrorFunctionT.html#acdc4ea93067f9630e4600d6471fe2553',1,'momentum::JointErrorFunctionT::JointErrorFunctionT(const Character &amp;character, const T &amp;lossAlpha=GeneralizedLossT&lt; T &gt;::kL2, const T &amp;lossC=T(1))']]],
  ['jointidentitytomodelidentity_3',['jointIdentityToModelIdentity',['../namespacemomentum.html#a9ea114b0a31b9c28d6780db87accc6cc',1,'momentum']]],
  ['jointtojointdistanceerrorfunctiont_4',['jointtojointdistanceerrorfunctiont',['../classmomentum_1_1JointToJointDistanceErrorFunctionT.html#afb560fa1b7a2479fbe7042701a3b5677',1,'momentum::JointToJointDistanceErrorFunctionT::JointToJointDistanceErrorFunctionT(const Skeleton &amp;skel, const ParameterTransform &amp;pt)'],['../classmomentum_1_1JointToJointDistanceErrorFunctionT.html#ae3cfeef24ed0a0ac2a2f6c681abc9610',1,'momentum::JointToJointDistanceErrorFunctionT::JointToJointDistanceErrorFunctionT(const Character &amp;character)']]],
  ['jointtojointorientationerrorfunctiont_5',['jointtojointorientationerrorfunctiont',['../classmomentum_1_1JointToJointOrientationErrorFunctionT.html#acefdaccc569c3d1c398e2713f4a8fed8',1,'momentum::JointToJointOrientationErrorFunctionT::JointToJointOrientationErrorFunctionT(const Skeleton &amp;skel, const ParameterTransform &amp;pt)'],['../classmomentum_1_1JointToJointOrientationErrorFunctionT.html#a4f69f068a4b6bf393ea4d7ed7715c6e7',1,'momentum::JointToJointOrientationErrorFunctionT::JointToJointOrientationErrorFunctionT(const Character &amp;character)']]],
  ['jointtojointpositionerrorfunctiont_6',['jointtojointpositionerrorfunctiont',['../classmomentum_1_1JointToJointPositionErrorFunctionT.html#a0d50c8c3eed8ce4ac6b8d19b3d5cbff5',1,'momentum::JointToJointPositionErrorFunctionT::JointToJointPositionErrorFunctionT(const Skeleton &amp;skel, const ParameterTransform &amp;pt)'],['../classmomentum_1_1JointToJointPositionErrorFunctionT.html#adb6065a686cdf025a1b25d604d377454',1,'momentum::JointToJointPositionErrorFunctionT::JointToJointPositionErrorFunctionT(const Character &amp;character)']]]
];
