Momentum: momentum::CollisionErrorFunctionT< T > Class Template Reference
momentum::CollisionErrorFunctionT< T > Class Template Reference
#include <collision_error_function.h>
Classes
struct CollisionPairInfo
Pre-computed valid collision pair with common ancestor.
Public Member Functions
CollisionErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt, const CollisionGeometry &cg, bool filterRestPoseOverlaps=true)
CollisionErrorFunctionT (const Character &character, bool filterRestPoseOverlaps=true)
double getError (const ModelParametersT< T > &params, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState) final
double getGradient (const ModelParametersT< T > &params, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, Ref< VectorX< T > > gradient) override
double getJacobian (const ModelParametersT< T > &, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, Ref< MatrixX< T > > jacobian, Ref< VectorX< T > > residual, int &usedRows) override
size_t getJacobianSize () const final
std::vector< Vector2i > getCollisionPairs () const
Public Member Functions inherited from momentum::SkeletonErrorFunctionT< T >
SkeletonErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt)
virtual ~SkeletonErrorFunctionT ()=default
const Skeleton & getSkeleton () const
const ParameterTransform & getParameterTransform () const
virtual const Character * getCharacter () const
For mesh-based error functions, get access to the underlying character.
void setWeight (T w)
T getWeight () const
void setActiveJoints (const VectorX< bool > &aj)
void setEnabledParameters (const ParameterSet &ps)
virtual double getGradient (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::VectorX< T > >)
virtual double getJacobian (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::MatrixX< T > >, Eigen::Ref< Eigen::VectorX< T > >, int &usedRows)
virtual void getHessian (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::MatrixX< T > >)
virtual double getSolverDerivatives (const ModelParametersT< T > &parameters, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, const size_t actualParameters, Eigen::MatrixX< T > &hess, Eigen::VectorX< T > &grad)
virtual bool needsMesh () const
Protected Member Functions
void updateCollisionPairs (bool filterRestPoseOverlaps=true)
void computeBroadPhase (const SkeletonStateT< T > &state)
Update collisionState_ and aabbs_ given the new skeleton state.
bool checkCollision (const CollisionGeometryStateT< T > &colState, size_t indexA, size_t indexB, T &distance, Vector2< T > &cp, T &overlap) const
AABB broadphase pre-check followed by narrow-phase capsule overlap test.
void accumulateGradientAlongChain (const SkeletonStateT< T > &state, const Vector3< T > &position, const Vector3< T > &direction, T weight, size_t startJoint, size_t stopJoint, Ref< VectorX< T > > gradient) const
Accumulate gradient contributions along a joint chain from startJoint up to (but not including) stopJoint.
void accumulateJacobianAlongChain (const SkeletonStateT< T > &state, const Vector3< T > &position, const Vector3< T > &direction, T factor, size_t startJoint, size_t stopJoint, Ref< MatrixX< T > > jacobian, int row) const
Accumulate Jacobian contributions along a joint chain from startJoint up to (but not including) stopJoint.
Protected Attributes
const CollisionGeometry collisionGeometry_
std::vector< CollisionPairInfo > validPairs_
Pre-filtered list of valid collision pairs (excludes rest-pose overlaps and adjacent joints).
std::vector< axel::BoundingBox< T > > aabbs_
Per-capsule AABBs, updated each frame for broadphase culling.
CollisionGeometryStateT< T > collisionState_
Protected Attributes inherited from momentum::SkeletonErrorFunctionT< T >
const Skeleton & skeleton_
const ParameterTransform & parameterTransform_
T weight_
VectorX< bool > activeJointParams_
ParameterSet enabledParameters_
bool useHessian_ {false}
Static Protected Attributes
static constexpr T kCollisionWeight = 5e-3f
Detailed Description
template<typename T>
class momentum::CollisionErrorFunctionT< T >
Definition at line 22 of file collision_error_function.h.
Constructor & Destructor Documentation
CollisionErrorFunctionT() [1/2]
template<typename T > momentum::CollisionErrorFunctionT< T >::CollisionErrorFunctionT (const Skeleton & skel, const ParameterTransform & pt, const CollisionGeometry & cg, bool filterRestPoseOverlaps = true) explicit
Parameters
filterRestPoseOverlaps When true (default), capsule pairs that overlap in the rest pose are excluded from collision checking. Set to false for characters where limbs are close to the body in bind pose (e.g., beefy characters) and you still want collision avoidance between those pairs.
Definition at line 21 of file collision_error_function.cpp.
References momentum::CollisionErrorFunctionT< T >::updateCollisionPairs().
CollisionErrorFunctionT() [2/2]
template<typename T > momentum::CollisionErrorFunctionT< T >::CollisionErrorFunctionT (const Character & character, bool filterRestPoseOverlaps = true) explicit
Definition at line 31 of file collision_error_function.cpp.
Member Function Documentation
accumulateGradientAlongChain()
template<typename T > void momentum::CollisionErrorFunctionT< T >::accumulateGradientAlongChain (const SkeletonStateT< T > & state, const Vector3< T > & position, const Vector3< T > & direction, T weight, size_t startJoint, size_t stopJoint, Ref< VectorX< T > > gradient) const protected
Accumulate gradient contributions along a joint chain from startJoint up to (but not including) stopJoint.
The sign of weight controls the push direction.
Definition at line 153 of file collision_error_function.cpp.
References jointIndex, momentum::kInvalidIndex, and momentum::kParametersPerJoint.
accumulateJacobianAlongChain()
template<typename T > void momentum::CollisionErrorFunctionT< T >::accumulateJacobianAlongChain (const SkeletonStateT< T > & state, const Vector3< T > & position, const Vector3< T > & direction, T factor, size_t startJoint, size_t stopJoint, Ref< MatrixX< T > > jacobian, int row) const protected
Accumulate Jacobian contributions along a joint chain from startJoint up to (but not including) stopJoint.
The sign of factor controls the push direction.
Definition at line 202 of file collision_error_function.cpp.
References jointIndex, momentum::kInvalidIndex, and momentum::kParametersPerJoint.
checkCollision()
template<typename T > bool momentum::CollisionErrorFunctionT< T >::checkCollision (const CollisionGeometryStateT< T > & colState, size_t indexA, size_t indexB, T & distance, Vector2< T > & cp, T & overlap) const protected
AABB broadphase pre-check followed by narrow-phase capsule overlap test.
Returns true if the pair collides, filling distance, cp, and overlap.
Definition at line 128 of file collision_error_function.cpp.
References distance, and momentum::overlaps().
computeBroadPhase()
template<typename T > void momentum::CollisionErrorFunctionT< T >::computeBroadPhase (const SkeletonStateT< T > & state) protected
Update collisionState_ and aabbs_ given the new skeleton state.
Definition at line 112 of file collision_error_function.cpp.
References MT_PROFILE_EVENT, and momentum::updateAabb().
getCollisionPairs()
template<typename T > std::vector< Vector2i > momentum::CollisionErrorFunctionT< T >::getCollisionPairs () const
Definition at line 252 of file collision_error_function.cpp.
References distance.
getError()
template<typename T > double momentum::CollisionErrorFunctionT< T >::getError (const ModelParametersT< T > & params, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState) final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 266 of file collision_error_function.cpp.
References distance, momentum::kParametersPerJoint, MT_CHECK, MT_LOGD, and momentum::sqr().
getGradient()
template<typename T > double momentum::CollisionErrorFunctionT< T >::getGradient (const ModelParametersT< T > & params, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState, Ref< VectorX< T > > gradient) override
Definition at line 304 of file collision_error_function.cpp.
References distance, momentum::kParametersPerJoint, MT_CHECK, momentum::sqr(), and wgt.
getJacobian()
template<typename T > double momentum::CollisionErrorFunctionT< T >::getJacobian (const ModelParametersT< T > & , const SkeletonStateT< T > & state, const MeshStateT< T > & meshState, Ref< MatrixX< T > > jacobian, Ref< VectorX< T > > residual, int & usedRows) override
Definition at line 359 of file collision_error_function.cpp.
References distance, momentum::kParametersPerJoint, MT_CHECK, MT_PROFILE_FUNCTION, momentum::sqr(), and wgt.
getJacobianSize()
template<typename T > size_t momentum::CollisionErrorFunctionT< T >::getJacobianSize () const final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 437 of file collision_error_function.cpp.
updateCollisionPairs()
template<typename T > void momentum::CollisionErrorFunctionT< T >::updateCollisionPairs (bool filterRestPoseOverlaps = true) protected
Definition at line 46 of file collision_error_function.cpp.
References distance, momentum::overlaps(), and momentum::updateAabb().
Referenced by momentum::CollisionErrorFunctionT< T >::CollisionErrorFunctionT().
Member Data Documentation
aabbs_
template<typename T > std::vector<axel::BoundingBox<T> > momentum::CollisionErrorFunctionT< T >::aabbs_ protected
Per-capsule AABBs, updated each frame for broadphase culling.
Definition at line 111 of file collision_error_function.h.
collisionGeometry_
template<typename T > const CollisionGeometry momentum::CollisionErrorFunctionT< T >::collisionGeometry_ protected
Definition at line 105 of file collision_error_function.h.
collisionState_
template<typename T > CollisionGeometryStateT<T> momentum::CollisionErrorFunctionT< T >::collisionState_ protected
Definition at line 113 of file collision_error_function.h.
kCollisionWeight
template<typename T > constexpr T momentum::CollisionErrorFunctionT< T >::kCollisionWeight = 5e-3f static constexpr protected
Definition at line 116 of file collision_error_function.h.
validPairs_
template<typename T > std::vector<CollisionPairInfo> momentum::CollisionErrorFunctionT< T >::validPairs_ protected
Pre-filtered list of valid collision pairs (excludes rest-pose overlaps and adjacent joints).
Definition at line 108 of file collision_error_function.h.
The documentation for this class was generated from the following files:
character_solver/collision_error_function.h
character_solver/collision_error_function.cpp