Momentum: momentum::SkeletonErrorFunctionT< T > Class Template Reference
momentum::SkeletonErrorFunctionT< T > Class Template Reference
#include <skeleton_error_function.h>
Public Member Functions
SkeletonErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt)
virtual ~SkeletonErrorFunctionT ()=default
const Skeleton & getSkeleton () const
const ParameterTransform & getParameterTransform () const
virtual const Character * getCharacter () const
For mesh-based error functions, get access to the underlying character.
void setWeight (T w)
T getWeight () const
void setActiveJoints (const VectorX< bool > &aj)
void setEnabledParameters (const ParameterSet &ps)
virtual double getError (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &)
virtual double getGradient (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::VectorX< T > >)
virtual double getJacobian (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::MatrixX< T > >, Eigen::Ref< Eigen::VectorX< T > >, int &usedRows)
virtual void getHessian (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::MatrixX< T > >)
virtual double getSolverDerivatives (const ModelParametersT< T > &parameters, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, const size_t actualParameters, Eigen::MatrixX< T > &hess, Eigen::VectorX< T > &grad)
virtual size_t getJacobianSize () const
virtual bool needsMesh () const
Protected Attributes
const Skeleton & skeleton_
const ParameterTransform & parameterTransform_
T weight_
VectorX< bool > activeJointParams_
ParameterSet enabledParameters_
bool useHessian_ {false}
Detailed Description
template<typename T>
class momentum::SkeletonErrorFunctionT< T >
Definition at line 19 of file skeleton_error_function.h.
Constructor & Destructor Documentation
SkeletonErrorFunctionT()
template<typename T > momentum::SkeletonErrorFunctionT< T >::SkeletonErrorFunctionT (const Skeleton & skel, const ParameterTransform & pt) inline
Definition at line 21 of file skeleton_error_function.h.
References momentum::SkeletonErrorFunctionT< T >::enabledParameters_.
~SkeletonErrorFunctionT()
template<typename T > virtual momentum::SkeletonErrorFunctionT< T >::~SkeletonErrorFunctionT () virtual default
Member Function Documentation
getCharacter()
template<typename T > virtual const Character * momentum::SkeletonErrorFunctionT< T >::getCharacter () const inline virtual
For mesh-based error functions, get access to the underlying character.
Error functions that depend only on the skeleton can return nullptr.
Reimplemented in momentum::VertexErrorFunctionT< T, Data, FuncDim >, momentum::VertexErrorFunctionT< T, VertexNormalDataT< T >, 1 >, momentum::VertexErrorFunctionT< T, VertexPlaneDataT< T >, 1 >, momentum::VertexErrorFunctionT< T, VertexPositionDataT< T >, 3 >, momentum::VertexErrorFunctionT< T, VertexProjectionDataT< T >, 2 >, momentum::FloorErrorFunctionT< T >, momentum::HeightErrorFunctionT< T >, momentum::PointTriangleVertexErrorFunctionT< T >, momentum::SkinnedLocatorErrorFunctionT< T >, momentum::SkinnedLocatorTriangleErrorFunctionT< T >, and momentum::VertexVertexDistanceErrorFunctionT< T >.
Definition at line 40 of file skeleton_error_function.h.
getError()
template<typename T > virtual double momentum::SkeletonErrorFunctionT< T >::getError (const ModelParametersT< T > & , const SkeletonStateT< T > & , const MeshStateT< T > &) inline virtual
Reimplemented in momentum::SkinnedLocatorErrorFunctionT< T >, momentum::FloorErrorFunctionT< T >, momentum::HeightErrorFunctionT< T >, momentum::PointTriangleVertexErrorFunctionT< T >, momentum::SkinnedLocatorTriangleErrorFunctionT< T >, momentum::VertexVertexDistanceErrorFunctionT< T >, momentum::ModelParametersErrorFunctionT< T >, momentum::FullyDifferentiableOrientationErrorFunctionT< T >, momentum::FullyDifferentiablePositionErrorFunctionT< T >, momentum::CameraProjectionErrorFunctionT< T >, momentum::CenterOfMassErrorFunctionT< T >, momentum::CollisionErrorFunctionT< T >, momentum::CollisionErrorFunctionStatelessT< T >, momentum::JointErrorFunctionT< T, Data, FuncDim, NumVec, NumPos >, momentum::JointErrorFunctionT< T, AimDataT< T >, 3, 2, 1 >, momentum::JointErrorFunctionT< T, FixedAxisDataT< T >, 1, 1, 0 >, momentum::JointErrorFunctionT< T, FixedAxisDataT< T >, 3, 1, 0 >, momentum::JointErrorFunctionT< T, NormalDataT< T >, 1, 2, 1 >, momentum::JointErrorFunctionT< T, OrientationDataT< T >, 9, 3, 0 >, momentum::JointErrorFunctionT< T, PlaneDataT< T >, 1 >, momentum::JointErrorFunctionT< T, PositionDataT< T > >, momentum::JointToJointDistanceErrorFunctionT< T >, momentum::JointToJointOrientationErrorFunctionT< T >, momentum::JointToJointPositionErrorFunctionT< T >, momentum::LimitErrorFunctionT< T >, momentum::PosePriorErrorFunctionT< T >, momentum::StateErrorFunctionT< T >, momentum::UnionErrorFunctionT< T >, momentum::SDFCollisionErrorFunctionT< T >, momentum::VertexErrorFunctionT< T, Data, FuncDim >, momentum::VertexErrorFunctionT< T, VertexNormalDataT< T >, 1 >, momentum::VertexErrorFunctionT< T, VertexPlaneDataT< T >, 1 >, momentum::VertexErrorFunctionT< T, VertexPositionDataT< T >, 3 >, momentum::VertexErrorFunctionT< T, VertexProjectionDataT< T >, 2 >, momentum::VertexSDFErrorFunctionT< T >, momentum::DistanceErrorFunctionT< T >, and momentum::ProjectionErrorFunctionT< T >.
Definition at line 60 of file skeleton_error_function.h.
getGradient()
template<typename T > virtual double momentum::SkeletonErrorFunctionT< T >::getGradient (const ModelParametersT< T > & , const SkeletonStateT< T > & , const MeshStateT< T > & , Eigen::Ref< Eigen::VectorX< T > >) inline virtual
Reimplemented in momentum::SkinnedLocatorErrorFunctionT< T >, momentum::FloorErrorFunctionT< T >, momentum::HeightErrorFunctionT< T >, momentum::PointTriangleVertexErrorFunctionT< T >, momentum::SkinnedLocatorTriangleErrorFunctionT< T >, momentum::VertexVertexDistanceErrorFunctionT< T >, momentum::CameraProjectionErrorFunctionT< T >, momentum::PosePriorErrorFunctionT< T >, momentum::StateErrorFunctionT< T >, momentum::UnionErrorFunctionT< T >, momentum::CenterOfMassErrorFunctionT< T >, momentum::SDFCollisionErrorFunctionT< T >, momentum::VertexErrorFunctionT< T, Data, FuncDim >, momentum::VertexErrorFunctionT< T, VertexNormalDataT< T >, 1 >, momentum::VertexErrorFunctionT< T, VertexPlaneDataT< T >, 1 >, momentum::VertexErrorFunctionT< T, VertexPositionDataT< T >, 3 >, momentum::VertexErrorFunctionT< T, VertexProjectionDataT< T >, 2 >, momentum::VertexNormalErrorFunctionT< T >, momentum::VertexPositionErrorFunctionT< T >, momentum::VertexSDFErrorFunctionT< T >, momentum::DistanceErrorFunctionT< T >, and momentum::ProjectionErrorFunctionT< T >.
Definition at line 67 of file skeleton_error_function.h.
Referenced by momentum::SkeletonErrorFunctionT< T >::getSolverDerivatives().
getHessian()
template<typename T > virtual void momentum::SkeletonErrorFunctionT< T >::getHessian (const ModelParametersT< T > & , const SkeletonStateT< T > & , const MeshStateT< T > & , Eigen::Ref< Eigen::MatrixX< T > >) inline virtual
Definition at line 86 of file skeleton_error_function.h.
References MT_THROW.
Referenced by momentum::SkeletonErrorFunctionT< T >::getSolverDerivatives().
getJacobian()
template<typename T > virtual double momentum::SkeletonErrorFunctionT< T >::getJacobian (const ModelParametersT< T > & , const SkeletonStateT< T > & , const MeshStateT< T > & , Eigen::Ref< Eigen::MatrixX< T > > , Eigen::Ref< Eigen::VectorX< T > > , int & usedRows) inline virtual
Reimplemented in momentum::SkinnedLocatorErrorFunctionT< T >, momentum::FloorErrorFunctionT< T >, momentum::HeightErrorFunctionT< T >, momentum::PointTriangleVertexErrorFunctionT< T >, momentum::SkinnedLocatorTriangleErrorFunctionT< T >, momentum::VertexVertexDistanceErrorFunctionT< T >, momentum::CameraProjectionErrorFunctionT< T >, momentum::PosePriorErrorFunctionT< T >, momentum::StateErrorFunctionT< T >, momentum::UnionErrorFunctionT< T >, momentum::CenterOfMassErrorFunctionT< T >, momentum::SDFCollisionErrorFunctionT< T >, momentum::VertexErrorFunctionT< T, Data, FuncDim >, momentum::VertexErrorFunctionT< T, VertexNormalDataT< T >, 1 >, momentum::VertexErrorFunctionT< T, VertexPlaneDataT< T >, 1 >, momentum::VertexErrorFunctionT< T, VertexPositionDataT< T >, 3 >, momentum::VertexErrorFunctionT< T, VertexProjectionDataT< T >, 2 >, momentum::VertexNormalErrorFunctionT< T >, momentum::VertexPositionErrorFunctionT< T >, momentum::VertexSDFErrorFunctionT< T >, momentum::DistanceErrorFunctionT< T >, and momentum::ProjectionErrorFunctionT< T >.
Definition at line 75 of file skeleton_error_function.h.
Referenced by momentum::SkeletonErrorFunctionT< T >::getSolverDerivatives().
getJacobianSize()
template<typename T > virtual size_t momentum::SkeletonErrorFunctionT< T >::getJacobianSize () const inline virtual
Reimplemented in momentum::CameraProjectionErrorFunctionT< T >, momentum::CenterOfMassErrorFunctionT< T >, momentum::CollisionErrorFunctionT< T >, momentum::CollisionErrorFunctionStatelessT< T >, momentum::DistanceErrorFunctionT< T >, momentum::FloorErrorFunctionT< T >, momentum::HeightErrorFunctionT< T >, momentum::JointErrorFunctionT< T, Data, FuncDim, NumVec, NumPos >, momentum::JointErrorFunctionT< T, AimDataT< T >, 3, 2, 1 >, momentum::JointErrorFunctionT< T, FixedAxisDataT< T >, 1, 1, 0 >, momentum::JointErrorFunctionT< T, FixedAxisDataT< T >, 3, 1, 0 >, momentum::JointErrorFunctionT< T, NormalDataT< T >, 1, 2, 1 >, momentum::JointErrorFunctionT< T, OrientationDataT< T >, 9, 3, 0 >, momentum::JointErrorFunctionT< T, PlaneDataT< T >, 1 >, momentum::JointErrorFunctionT< T, PositionDataT< T > >, momentum::JointToJointDistanceErrorFunctionT< T >, momentum::JointToJointOrientationErrorFunctionT< T >, momentum::JointToJointPositionErrorFunctionT< T >, momentum::LimitErrorFunctionT< T >, momentum::ModelParametersErrorFunctionT< T >, momentum::PointTriangleVertexErrorFunctionT< T >, momentum::PosePriorErrorFunctionT< T >, momentum::ProjectionErrorFunctionT< T >, momentum::SkinnedLocatorErrorFunctionT< T >, momentum::SkinnedLocatorTriangleErrorFunctionT< T >, momentum::StateErrorFunctionT< T >, momentum::VertexErrorFunctionT< T, Data, FuncDim >, momentum::VertexErrorFunctionT< T, VertexNormalDataT< T >, 1 >, momentum::VertexErrorFunctionT< T, VertexPlaneDataT< T >, 1 >, momentum::VertexErrorFunctionT< T, VertexPositionDataT< T >, 3 >, momentum::VertexErrorFunctionT< T, VertexProjectionDataT< T >, 2 >, momentum::VertexVertexDistanceErrorFunctionT< T >, momentum::FullyDifferentiableOrientationErrorFunctionT< T >, momentum::FullyDifferentiablePositionErrorFunctionT< T >, momentum::UnionErrorFunctionT< T >, momentum::SDFCollisionErrorFunctionT< T >, and momentum::VertexSDFErrorFunctionT< T >.
Definition at line 135 of file skeleton_error_function.h.
Referenced by momentum::SkeletonErrorFunctionT< T >::getSolverDerivatives().
getParameterTransform()
template<typename T > const ParameterTransform & momentum::SkeletonErrorFunctionT< T >::getParameterTransform () const inline
Definition at line 34 of file skeleton_error_function.h.
References momentum::SkeletonErrorFunctionT< T >::parameterTransform_.
getSkeleton()
template<typename T > const Skeleton & momentum::SkeletonErrorFunctionT< T >::getSkeleton () const inline
Definition at line 30 of file skeleton_error_function.h.
References momentum::SkeletonErrorFunctionT< T >::skeleton_.
getSolverDerivatives()
template<typename T > virtual double momentum::SkeletonErrorFunctionT< T >::getSolverDerivatives (const ModelParametersT< T > & parameters, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState, const size_t actualParameters, Eigen::MatrixX< T > & hess, Eigen::VectorX< T > & grad) inline virtual
Definition at line 94 of file skeleton_error_function.h.
References momentum::SkeletonErrorFunctionT< T >::getGradient(), momentum::SkeletonErrorFunctionT< T >::getHessian(), momentum::SkeletonErrorFunctionT< T >::getJacobian(), momentum::SkeletonErrorFunctionT< T >::getJacobianSize(), momentum::EigenStrongType< Derived, EigenType >::size(), and momentum::SkeletonErrorFunctionT< T >::useHessian_.
getWeight()
template<typename T > T momentum::SkeletonErrorFunctionT< T >::getWeight () const inline
Definition at line 48 of file skeleton_error_function.h.
References momentum::SkeletonErrorFunctionT< T >::weight_.
needsMesh()
template<typename T > virtual bool momentum::SkeletonErrorFunctionT< T >::needsMesh () const inline virtual
Reimplemented in momentum::VertexErrorFunctionT< T, Data, FuncDim >, momentum::VertexErrorFunctionT< T, VertexNormalDataT< T >, 1 >, momentum::VertexErrorFunctionT< T, VertexPlaneDataT< T >, 1 >, momentum::VertexErrorFunctionT< T, VertexPositionDataT< T >, 3 >, momentum::VertexErrorFunctionT< T, VertexProjectionDataT< T >, 2 >, momentum::FloorErrorFunctionT< T >, momentum::HeightErrorFunctionT< T >, momentum::PointTriangleVertexErrorFunctionT< T >, momentum::SDFCollisionErrorFunctionT< T >, momentum::SkinnedLocatorTriangleErrorFunctionT< T >, momentum::VertexSDFErrorFunctionT< T >, and momentum::VertexVertexDistanceErrorFunctionT< T >.
Definition at line 139 of file skeleton_error_function.h.
setActiveJoints()
template<typename T > void momentum::SkeletonErrorFunctionT< T >::setActiveJoints (const VectorX< bool > & aj) inline
Definition at line 52 of file skeleton_error_function.h.
References momentum::SkeletonErrorFunctionT< T >::activeJointParams_.
setEnabledParameters()
template<typename T > void momentum::SkeletonErrorFunctionT< T >::setEnabledParameters (const ParameterSet & ps) inline
Definition at line 56 of file skeleton_error_function.h.
References momentum::SkeletonErrorFunctionT< T >::enabledParameters_.
setWeight()
template<typename T > void momentum::SkeletonErrorFunctionT< T >::setWeight (T w) inline
Definition at line 44 of file skeleton_error_function.h.
References momentum::SkeletonErrorFunctionT< T >::weight_.
Member Data Documentation
activeJointParams_
template<typename T > VectorX<bool> momentum::SkeletonErrorFunctionT< T >::activeJointParams_ protected
Definition at line 147 of file skeleton_error_function.h.
Referenced by momentum::SkeletonErrorFunctionT< T >::setActiveJoints().
enabledParameters_
template<typename T > ParameterSet momentum::SkeletonErrorFunctionT< T >::enabledParameters_ protected
Definition at line 148 of file skeleton_error_function.h.
Referenced by momentum::SkeletonErrorFunctionT< T >::setEnabledParameters(), and momentum::SkeletonErrorFunctionT< T >::SkeletonErrorFunctionT().
parameterTransform_
template<typename T > const ParameterTransform& momentum::SkeletonErrorFunctionT< T >::parameterTransform_ protected
Definition at line 145 of file skeleton_error_function.h.
Referenced by momentum::SkeletonErrorFunctionT< T >::getParameterTransform().
skeleton_
template<typename T > const Skeleton& momentum::SkeletonErrorFunctionT< T >::skeleton_ protected
Definition at line 144 of file skeleton_error_function.h.
Referenced by momentum::SkeletonErrorFunctionT< T >::getSkeleton(), and momentum::StateErrorFunctionT< T >::StateErrorFunctionT().
useHessian_
template<typename T > bool momentum::SkeletonErrorFunctionT< T >::useHessian_ {false} protected
Definition at line 149 of file skeleton_error_function.h.
Referenced by momentum::SkeletonErrorFunctionT< T >::getSolverDerivatives().
weight_
template<typename T > T momentum::SkeletonErrorFunctionT< T >::weight_ protected
Definition at line 146 of file skeleton_error_function.h.
Referenced by momentum::SkeletonErrorFunctionT< T >::getWeight(), and momentum::SkeletonErrorFunctionT< T >::setWeight().
The documentation for this class was generated from the following files:
character_solver/fwd.h
character_solver/skeleton_error_function.h