Momentum: momentum::FiniteDifferenceSequenceErrorFunctionT< T > Class Template Reference
momentum::FiniteDifferenceSequenceErrorFunctionT< T > Class Template Reference
Base class for error functions that penalize finite difference derivatives of joint positions across consecutive frames using a configurable stencil.
#include <finite_difference_sequence_error_function.h>
Public Member Functions
FiniteDifferenceSequenceErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt, const std::vector< T > &stencilCoefficients)
FiniteDifferenceSequenceErrorFunctionT (const Character &character, const std::vector< T > &stencilCoefficients)
size_t numFrames () const final
double getError (std::span< const ModelParametersT< T > > modelParameters, std::span< const SkeletonStateT< T > > skelStates, std::span< const MeshStateT< T > > meshStates) const final
double getGradient (std::span< const ModelParametersT< T > > modelParameters, std::span< const SkeletonStateT< T > > skelStates, std::span< const MeshStateT< T > > meshStates, Eigen::Ref< Eigen::VectorX< T > > gradient) const final
double getJacobian (std::span< const ModelParametersT< T > > modelParameters, std::span< const SkeletonStateT< T > > skelStates, std::span< const MeshStateT< T > > meshStates, Eigen::Ref< Eigen::MatrixX< T > > jacobian, Eigen::Ref< Eigen::VectorX< T > > residual, int &usedRows) const final
size_t getJacobianSize () const final
void setTargetWeights (const Eigen::VectorX< T > &weights)
Set the per-joint weights for the derivative error.
void setTargetValue (const Eigen::Vector3< T > &targetValue)
Set a single target value applied to all joints.
void setTargetValues (const std::vector< Eigen::Vector3< T > > &targetValues)
Set per-joint target values.
void reset ()
Reset weights to ones and target values to zero.
const Eigen::VectorX< T > & getTargetWeights () const
const std::vector< Eigen::Vector3< T > > & getTargetValues () const
const std::vector< T > & getStencilCoefficients () const
Public Member Functions inherited from momentum::SequenceErrorFunctionT< T >
SequenceErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt)
virtual ~SequenceErrorFunctionT ()=default
void setWeight (T w)
float getWeight () const
void setActiveJoints (const VectorX< bool > &aj)
void setEnabledParameters (const ParameterSet &ps)
virtual bool needsMesh () const
const Skeleton & getSkeleton () const
const ParameterTransform & getParameterTransform () const
Additional Inherited Members
Protected Attributes inherited from momentum::SequenceErrorFunctionT< T >
const Skeleton & skeleton_
const ParameterTransform & parameterTransform_
T weight_ = 1.0f
VectorX< bool > activeJointParams_
ParameterSet enabledParameters_
Detailed Description
template<typename T>
class momentum::FiniteDifferenceSequenceErrorFunctionT< T >
Base class for error functions that penalize finite difference derivatives of joint positions across consecutive frames using a configurable stencil.
This class provides a generic framework for computing derivatives of arbitrary order using finite difference stencils. Derived classes specify the stencil coefficients to compute specific derivatives:
2nd derivative (acceleration): [-1, 2, -1] stencil, 3 frames
3rd derivative (jerk): [1, -3, 3, -1] stencil, 4 frames
The residual for each joint is computed as: derivative = sum(stencilCoefficients[i] * pos[t+i]) - targetValue
Note: This error function only constrains position derivatives, not rotation derivatives, as rotation derivatives involve significantly more complex mathematics.
Definition at line 31 of file finite_difference_sequence_error_function.h.
Constructor & Destructor Documentation
FiniteDifferenceSequenceErrorFunctionT() [1/2]
template<typename T > momentum::FiniteDifferenceSequenceErrorFunctionT< T >::FiniteDifferenceSequenceErrorFunctionT (const Skeleton & skel, const ParameterTransform & pt, const std::vector< T > & stencilCoefficients)
Definition at line 19 of file finite_difference_sequence_error_function.cpp.
References MT_CHECK.
FiniteDifferenceSequenceErrorFunctionT() [2/2]
template<typename T > momentum::FiniteDifferenceSequenceErrorFunctionT< T >::FiniteDifferenceSequenceErrorFunctionT (const Character & character, const std::vector< T > & stencilCoefficients) explicit
Definition at line 30 of file finite_difference_sequence_error_function.cpp.
Member Function Documentation
getError()
template<typename T > double momentum::FiniteDifferenceSequenceErrorFunctionT< T >::getError (std::span< const ModelParametersT< T > > modelParameters, std::span< const SkeletonStateT< T > > skelStates, std::span< const MeshStateT< T > > meshStates) const final virtual
Reimplemented from momentum::SequenceErrorFunctionT< T >.
Definition at line 64 of file finite_difference_sequence_error_function.cpp.
References MT_CHECK, and MT_PROFILE_FUNCTION.
getGradient()
template<typename T > double momentum::FiniteDifferenceSequenceErrorFunctionT< T >::getGradient (std::span< const ModelParametersT< T > > modelParameters, std::span< const SkeletonStateT< T > > skelStates, std::span< const MeshStateT< T > > meshStates, Eigen::Ref< Eigen::VectorX< T > > gradient) const final virtual
Reimplemented from momentum::SequenceErrorFunctionT< T >.
Definition at line 95 of file finite_difference_sequence_error_function.cpp.
References momentum::kInvalidIndex, momentum::kParametersPerJoint, MT_CHECK, MT_PROFILE_FUNCTION, and wgt.
getJacobian()
template<typename T > double momentum::FiniteDifferenceSequenceErrorFunctionT< T >::getJacobian (std::span< const ModelParametersT< T > > modelParameters, std::span< const SkeletonStateT< T > > skelStates, std::span< const MeshStateT< T > > meshStates, Eigen::Ref< Eigen::MatrixX< T > > jacobian, Eigen::Ref< Eigen::VectorX< T > > residual, int & usedRows) const final virtual
Reimplemented from momentum::SequenceErrorFunctionT< T >.
Definition at line 194 of file finite_difference_sequence_error_function.cpp.
References momentum::kInvalidIndex, momentum::kParametersPerJoint, MT_CHECK, MT_PROFILE_FUNCTION, offset, and wgt.
getJacobianSize()
template<typename T > size_t momentum::FiniteDifferenceSequenceErrorFunctionT< T >::getJacobianSize () const final virtual
Reimplemented from momentum::SequenceErrorFunctionT< T >.
Definition at line 187 of file finite_difference_sequence_error_function.cpp.
getStencilCoefficients()
template<typename T > const std::vector< T > & momentum::FiniteDifferenceSequenceErrorFunctionT< T >::getStencilCoefficients () const inline
Definition at line 91 of file finite_difference_sequence_error_function.h.
getTargetValues()
template<typename T > const std::vector< Eigen::Vector3< T > > & momentum::FiniteDifferenceSequenceErrorFunctionT< T >::getTargetValues () const inline
Definition at line 87 of file finite_difference_sequence_error_function.h.
Referenced by momentum::AccelerationSequenceErrorFunctionT< T >::getTargetAccelerations(), and momentum::JerkSequenceErrorFunctionT< T >::getTargetJerks().
getTargetWeights()
template<typename T > const Eigen::VectorX< T > & momentum::FiniteDifferenceSequenceErrorFunctionT< T >::getTargetWeights () const inline
Definition at line 83 of file finite_difference_sequence_error_function.h.
Referenced by momentum::AccelerationSequenceErrorFunctionT< T >::getTargetWeights(), and momentum::JerkSequenceErrorFunctionT< T >::getTargetWeights().
numFrames()
template<typename T > size_t momentum::FiniteDifferenceSequenceErrorFunctionT< T >::numFrames () const inline final virtual
Implements momentum::SequenceErrorFunctionT< T >.
Definition at line 41 of file finite_difference_sequence_error_function.h.
reset()
template<typename T > void momentum::FiniteDifferenceSequenceErrorFunctionT< T >::reset ()
Reset weights to ones and target values to zero.
Definition at line 39 of file finite_difference_sequence_error_function.cpp.
Referenced by momentum::AccelerationSequenceErrorFunctionT< T >::reset(), and momentum::JerkSequenceErrorFunctionT< T >::reset().
setTargetValue()
template<typename T > void momentum::FiniteDifferenceSequenceErrorFunctionT< T >::setTargetValue (const Eigen::Vector3< T > & targetValue)
Set a single target value applied to all joints.
This is a convenience method for uniform targets (e.g., gravity for acceleration).
Parameters
targetValue The target derivative value (e.g., (0, -9.8, 0) * dt^2 for gravity acceleration).
Definition at line 51 of file finite_difference_sequence_error_function.cpp.
Referenced by momentum::AccelerationSequenceErrorFunctionT< T >::setTargetAcceleration(), and momentum::JerkSequenceErrorFunctionT< T >::setTargetJerk().
setTargetValues()
template<typename T > void momentum::FiniteDifferenceSequenceErrorFunctionT< T >::setTargetValues (const std::vector< Eigen::Vector3< T > > & targetValues)
Set per-joint target values.
Parameters
targetValues Vector of target derivative values, one per joint.
Definition at line 57 of file finite_difference_sequence_error_function.cpp.
References MT_CHECK.
Referenced by momentum::AccelerationSequenceErrorFunctionT< T >::setTargetAccelerations(), and momentum::JerkSequenceErrorFunctionT< T >::setTargetJerks().
setTargetWeights()
template<typename T > void momentum::FiniteDifferenceSequenceErrorFunctionT< T >::setTargetWeights (const Eigen::VectorX< T > & weights)
Set the per-joint weights for the derivative error.
Parameters
weights Per-joint weights vector. Size must match the number of joints.
Definition at line 45 of file finite_difference_sequence_error_function.cpp.
References MT_CHECK.
Referenced by momentum::AccelerationSequenceErrorFunctionT< T >::setTargetWeights(), and momentum::JerkSequenceErrorFunctionT< T >::setTargetWeights().
The documentation for this class was generated from the following files:
character_sequence_solver/finite_difference_sequence_error_function.h
character_sequence_solver/finite_difference_sequence_error_function.cpp