Momentum: momentum::fbx_internal Namespace Reference
momentum::fbx_internal Namespace Reference
Classes
struct JointCurveSetup
struct MeshBlendShapeResult
struct SkeletonNodeResult
Functions
::fbxsdk::FbxAxisSystem::EUpVector toFbx (const FbxUpVector upVector)
::fbxsdk::FbxAxisSystem::EFrontVector toFbx (const FbxFrontVector frontVector)
::fbxsdk::FbxAxisSystem::ECoordSystem toFbx (const FbxCoordSystem coordSystem)
::fbxsdk::FbxAxisSystem toFbx (const FbxCoordSystemInfo &coordSystemInfo)
void setFrameRate (::fbxsdk::FbxScene *scene, const double framerate)
SkeletonNodeResult createSkeletonNodes (const Character &character, ::fbxsdk::FbxScene *scene)
void addMetaData (::fbxsdk::FbxNode *skeletonRootNode, const Character &character)
void createLocatorNodes (const Character &character, ::fbxsdk::FbxScene *scene, const std::vector<::fbxsdk::FbxNode * > &skeletonNodes)
void createCollisionGeometryNodes (const Character &character, ::fbxsdk::FbxScene *scene, const std::vector<::fbxsdk::FbxNode * > &skeletonNodes)
std::pair<::fbxsdk::FbxAnimStack *, ::fbxsdk::FbxAnimLayer * > getOrCreateAnimStackAndLayer (::fbxsdk::FbxScene *scene, const char *stackName)
float jointParamToFbx (float value, size_t curveOffset, const Joint &joint)
Convert a raw momentum joint parameter to the FBX-native value.
JointCurveSetup setupJointAnimCurves (const Character &character, const std::vector<::fbxsdk::FbxNode * > &skeletonNodes, ::fbxsdk::FbxAnimLayer *animBaseLayer, const bool skipActiveJointParamCheck)
void createAnimationCurves (const Character &character, ::fbxsdk::FbxScene *scene, const std::vector<::fbxsdk::FbxNode * > &skeletonNodes, const MatrixXf &jointValues, const double framerate, const bool skipActiveJointParamCheck)
void saveSkinWeightsToFbx (const Character &character, ::fbxsdk::FbxScene *scene, ::fbxsdk::FbxMesh *mesh, const std::unordered_map< size_t, fbxsdk::FbxNode * > &jointToNodeMap)
void writePolygonsToFbxMesh (const Mesh &mesh, ::fbxsdk::FbxMesh *lMesh)
void writeTextureUVIndicesToFbxMesh (const Mesh &mesh, ::fbxsdk::FbxMesh *lMesh, fbxsdk::FbxLayerElement::EType uvType)
std::vector<::fbxsdk::FbxBlendShapeChannel * > saveBlendShapeGeometryToFbx (const BlendShapeBase &blendShape, ::fbxsdk::FbxScene *scene, ::fbxsdk::FbxMesh *mesh, const std::string &deformerName, const std::string &channelPrefix)
void createBlendShapeAnimationCurves (::fbxsdk::FbxScene *scene, const std::vector<::fbxsdk::FbxBlendShapeChannel * > &channels, const MatrixXf &weights, const double framerate)
MeshBlendShapeResult createMeshNode (const Character &character, ::fbxsdk::FbxScene *scene, ::fbxsdk::FbxNode *parentNode, const std::unordered_map< size_t, fbxsdk::FbxNode * > &jointToNodeMap, Permissive permissive, const std::string &meshName="body_mesh")
MatrixXf extractBlendShapeWeights (const Character &character, const MatrixXf &poses)
MatrixXf extractFaceExpressionWeights (const Character &character, const MatrixXf &poses)
std::vector<::fbxsdk::FbxNode * > createMarkerNodes (::fbxsdk::FbxScene *scene, std::span< const std::vector< Marker > > markerSequence, const double framerate)
void prependNamespaceToAllNodes (::fbxsdk::FbxNode *node, const std::string &namespacePrefix)
Variables
constexpr const char * kMomentumMarkersRootProperty = "Momentum_Markers_Root"
constexpr const char * kMomentumMarkerProperty = "Momentum_Marker"
Function Documentation
addMetaData()
void momentum::fbx_internal::addMetaData (::fbxsdk::FbxNode * skeletonRootNode, const Character & character) inline
Definition at line 183 of file fbx_io_internal.h.
References momentum::CharacterT< T >::metadata, and momentum::CharacterT< T >::name.
createAnimationCurves()
void momentum::fbx_internal::createAnimationCurves (const Character & character, ::fbxsdk::FbxScene * scene, const std::vector<::fbxsdk::FbxNode * > & skeletonNodes, const MatrixXf & jointValues, const double framerate, const bool skipActiveJointParamCheck) inline
Definition at line 383 of file fbx_io_internal.h.
References momentum::ParameterTransformT< T >::activeJointParams, getOrCreateAnimStackAndLayer(), jointIndex, jointParamToFbx(), momentum::SkeletonT< T >::joints, momentum::kParametersPerJoint, momentum::CharacterT< T >::parameterTransform, setFrameRate(), setupJointAnimCurves(), and momentum::CharacterT< T >::skeleton.
createBlendShapeAnimationCurves()
void momentum::fbx_internal::createBlendShapeAnimationCurves (::fbxsdk::FbxScene * scene, const std::vector<::fbxsdk::FbxBlendShapeChannel * > & channels, const MatrixXf & weights, const double framerate) inline
Definition at line 574 of file fbx_io_internal.h.
References channels, getOrCreateAnimStackAndLayer(), and setFrameRate().
createCollisionGeometryNodes()
void momentum::fbx_internal::createCollisionGeometryNodes (const Character & character, ::fbxsdk::FbxScene * scene, const std::vector<::fbxsdk::FbxNode * > & skeletonNodes) inline
Definition at line 217 of file fbx_io_internal.h.
References momentum::CharacterT< T >::collision, momentum::Extrinsic, momentum::kInvalidIndex, MT_LOGD, MT_LOGE, MT_THROW_IF, momentum::toDeg(), and u.
createLocatorNodes()
void momentum::fbx_internal::createLocatorNodes (const Character & character, ::fbxsdk::FbxScene * scene, const std::vector<::fbxsdk::FbxNode * > & skeletonNodes) inline
Definition at line 194 of file fbx_io_internal.h.
References momentum::kInvalidIndex, momentum::CharacterT< T >::locators, and MT_THROW_IF.
createMarkerNodes()
std::vector<::fbxsdk::FbxNode * > momentum::fbx_internal::createMarkerNodes (::fbxsdk::FbxScene * scene, std::span< const std::vector< Marker > > markerSequence, const double framerate) inline
Definition at line 737 of file fbx_io_internal.h.
References getOrCreateAnimStackAndLayer(), kMomentumMarkerProperty, kMomentumMarkersRootProperty, MT_THROW_IF, and setFrameRate().
createMeshNode()
MeshBlendShapeResult momentum::fbx_internal::createMeshNode (const Character & character, ::fbxsdk::FbxScene * scene, ::fbxsdk::FbxNode * parentNode, const std::unordered_map< size_t, fbxsdk::FbxNode * > & jointToNodeMap, Permissive permissive, const std::string & meshName = "body_mesh") inline
Definition at line 611 of file fbx_io_internal.h.
References momentum::CharacterT< T >::blendShape, momentum::fbx_internal::MeshBlendShapeResult::blendShapeChannels, momentum::fbx_internal::MeshBlendShapeResult::faceExprChannels, momentum::CharacterT< T >::faceExpressionBlendShape, momentum::CharacterT< T >::mesh, MT_THROW_IF, momentum::CharacterT< T >::name, momentum::No, momentum::normal(), saveBlendShapeGeometryToFbx(), saveSkinWeightsToFbx(), momentum::CharacterT< T >::skinWeights, writePolygonsToFbxMesh(), and writeTextureUVIndicesToFbxMesh().
createSkeletonNodes()
SkeletonNodeResult momentum::fbx_internal::createSkeletonNodes (const Character & character, ::fbxsdk::FbxScene * scene) inline
Definition at line 128 of file fbx_io_internal.h.
References momentum::SkeletonT< T >::joints, momentum::fbx_internal::SkeletonNodeResult::jointToNodeMap, momentum::kInvalidIndex, MT_THROW_IF, momentum::fbx_internal::SkeletonNodeResult::nodes, momentum::fbx_internal::SkeletonNodeResult::rootNode, momentum::rotationMatrixToEulerZYX(), momentum::CharacterT< T >::skeleton, and momentum::toDeg().
extractBlendShapeWeights()
MatrixXf momentum::fbx_internal::extractBlendShapeWeights (const Character & character, const MatrixXf & poses) inline
Definition at line 689 of file fbx_io_internal.h.
References momentum::CharacterT< T >::blendShape, momentum::ParameterTransformT< T >::blendShapeParameters, and momentum::CharacterT< T >::parameterTransform.
extractFaceExpressionWeights()
MatrixXf momentum::fbx_internal::extractFaceExpressionWeights (const Character & character, const MatrixXf & poses) inline
Definition at line 709 of file fbx_io_internal.h.
References momentum::CharacterT< T >::faceExpressionBlendShape, momentum::ParameterTransformT< T >::faceExpressionParameters, and momentum::CharacterT< T >::parameterTransform.
getOrCreateAnimStackAndLayer()
std::pair<::fbxsdk::FbxAnimStack *, ::fbxsdk::FbxAnimLayer * > momentum::fbx_internal::getOrCreateAnimStackAndLayer (::fbxsdk::FbxScene * scene, const char * stackName) inline
Definition at line 270 of file fbx_io_internal.h.
Referenced by createAnimationCurves(), createBlendShapeAnimationCurves(), and createMarkerNodes().
jointParamToFbx()
float momentum::fbx_internal::jointParamToFbx (float value, size_t curveOffset, const Joint & joint) inline
Convert a raw momentum joint parameter to the FBX-native value.
FBX curves use 9 channels per joint: tx,ty,tz (0-2), rx,ry,rz (3-5), sx,sy,sz (6-8). Momentum stores 7 params: translation, rotation (radians), uniform log2-scale.
Translation: adds the joint's rest-pose translationOffset.
Rotation: converts radians to degrees.
Scale: converts log2 to linear (exp2).
Parameters
value Raw joint parameter value from the motion matrix.
curveOffset FBX curve channel index (0-8).
joint The joint providing the translation offset.
Definition at line 302 of file fbx_io_internal.h.
References momentum::toDeg().
Referenced by createAnimationCurves().
prependNamespaceToAllNodes()
void momentum::fbx_internal::prependNamespaceToAllNodes (::fbxsdk::FbxNode * node, const std::string & namespacePrefix) inline
Definition at line 858 of file fbx_io_internal.h.
References prependNamespaceToAllNodes().
Referenced by prependNamespaceToAllNodes().
saveBlendShapeGeometryToFbx()
std::vector<::fbxsdk::FbxBlendShapeChannel * > momentum::fbx_internal::saveBlendShapeGeometryToFbx (const BlendShapeBase & blendShape, ::fbxsdk::FbxScene * scene, ::fbxsdk::FbxMesh * mesh, const std::string & deformerName, const std::string & channelPrefix) inline
Definition at line 530 of file fbx_io_internal.h.
References channels, momentum::BlendShapeBase::getShapeNames(), momentum::BlendShapeBase::getShapeVectors(), and momentum::BlendShapeBase::shapeSize().
Referenced by createMeshNode().
saveSkinWeightsToFbx()
void momentum::fbx_internal::saveSkinWeightsToFbx (const Character & character, ::fbxsdk::FbxScene * scene, ::fbxsdk::FbxMesh * mesh, const std::unordered_map< size_t, fbxsdk::FbxNode * > & jointToNodeMap) inline
Definition at line 427 of file fbx_io_internal.h.
References momentum::CharacterT< T >::skinWeights.
Referenced by createMeshNode().
setFrameRate()
void momentum::fbx_internal::setFrameRate (::fbxsdk::FbxScene * scene, const double framerate) inline
Definition at line 91 of file fbx_io_internal.h.
Referenced by createAnimationCurves(), createBlendShapeAnimationCurves(), and createMarkerNodes().
setupJointAnimCurves()
JointCurveSetup momentum::fbx_internal::setupJointAnimCurves (const Character & character, const std::vector<::fbxsdk::FbxNode * > & skeletonNodes, ::fbxsdk::FbxAnimLayer * animBaseLayer, const bool skipActiveJointParamCheck) inline
Definition at line 318 of file fbx_io_internal.h.
References momentum::ParameterTransformT< T >::activeJointParams, momentum::fbx_internal::JointCurveSetup::animCurves, jointIndex, momentum::SkeletonT< T >::joints, momentum::kParametersPerJoint, momentum::CharacterT< T >::parameterTransform, and momentum::CharacterT< T >::skeleton.
Referenced by createAnimationCurves().
toFbx() [1/4]
::fbxsdk::FbxAxisSystem::ECoordSystem momentum::fbx_internal::toFbx (const FbxCoordSystem coordSystem) inline
Definition at line 69 of file fbx_io_internal.h.
References momentum::LeftHanded, MT_THROW, and momentum::RightHanded.
toFbx() [2/4]
::fbxsdk::FbxAxisSystem momentum::fbx_internal::toFbx (const FbxCoordSystemInfo & coordSystemInfo) inline
Definition at line 80 of file fbx_io_internal.h.
References momentum::FbxCoordSystemInfo::coordSystem, momentum::FbxCoordSystemInfo::frontVector, toFbx(), and momentum::FbxCoordSystemInfo::upVector.
toFbx() [3/4]
::fbxsdk::FbxAxisSystem::EFrontVector momentum::fbx_internal::toFbx (const FbxFrontVector frontVector) inline
Definition at line 58 of file fbx_io_internal.h.
References MT_THROW, momentum::ParityEven, and momentum::ParityOdd.
toFbx() [4/4]
::fbxsdk::FbxAxisSystem::EUpVector momentum::fbx_internal::toFbx (const FbxUpVector upVector) inline
Definition at line 45 of file fbx_io_internal.h.
References MT_THROW, momentum::XAxis, momentum::YAxis, and momentum::ZAxis.
Referenced by toFbx().
writePolygonsToFbxMesh()
void momentum::fbx_internal::writePolygonsToFbxMesh (const Mesh & mesh, ::fbxsdk::FbxMesh * lMesh) inline
Definition at line 473 of file fbx_io_internal.h.
References momentum::MeshT< T >::faces, offset, momentum::MeshT< T >::polyFaces, and momentum::MeshT< T >::polyFaceSizes.
Referenced by createMeshNode().
writeTextureUVIndicesToFbxMesh()
void momentum::fbx_internal::writeTextureUVIndicesToFbxMesh (const Mesh & mesh, ::fbxsdk::FbxMesh * lMesh, fbxsdk::FbxLayerElement::EType uvType) inline
Definition at line 495 of file fbx_io_internal.h.
References offset, momentum::MeshT< T >::polyFaces, momentum::MeshT< T >::polyFaceSizes, momentum::MeshT< T >::polyTexcoordFaces, and momentum::MeshT< T >::texcoord_faces.
Referenced by createMeshNode().
Variable Documentation
kMomentumMarkerProperty
constexpr const char* momentum::fbx_internal::kMomentumMarkerProperty = "Momentum_Marker" constexpr
Definition at line 735 of file fbx_io_internal.h.
Referenced by createMarkerNodes().
kMomentumMarkersRootProperty
constexpr const char* momentum::fbx_internal::kMomentumMarkersRootProperty = "Momentum_Markers_Root" constexpr
Definition at line 734 of file fbx_io_internal.h.
Referenced by createMarkerNodes().