Momentum: momentum::ParameterTransformT< T > Struct Template Reference
momentum::ParameterTransformT< T > Struct Template Reference
A parameter transform is an abstraction of the joint parameters that maps a model_parameter vector to a joint_parameter vector.
#include <parameter_transform.h>
Public Member Functions
VectorX< bool > computeActiveJointParams (const ParameterSet &ps=allParams()) const
Compute activeJointParams based on the transform and the input ParameterSet.
size_t getParameterIdByName (const std::string &nm) const
Return the index of a model parameter from its name.
JointParametersT< T > apply (const ModelParametersT< T > &parameters) const
Map model parameters to joint parameters using a linear transformation.
JointParametersT< T > apply (const CharacterParametersT< T > &parameters) const
Map model parameters to joint parameters using a linear transformation.
JointParametersT< T > zero () const
Return rest pose joint parameters.
JointParametersT< T > bindPose () const
Return bind pose joint parameters (same as the rest pose here).
ParameterSet getScalingParameters () const
Get a list of scaling parameters (with prefix "scale_").
ParameterSet getRigidParameters () const
Get a list of root parameters (with prefix "root_")
ParameterSet getPoseParameters () const
Return all parameters used for posing the body (excludes scaling parameters, blend shape parameters, or any parameters used for physics).
ParameterSet getBlendShapeParameters () const
Get a list of blend shape parameters.
ParameterSet getFaceExpressionParameters () const
Get a list of face expression parameters.
ParameterSet getSkinnedLocatorParameters () const
Get a list of skinned locator parameters.
ParameterSet getParameterSet (const std::string &parameterSetName, bool allowMissing=false) const
Get a parameter set, if allowMissing is set then it will return an empty parameter set if no such parameterset is found in the file.
template<typename T2 >
ParameterTransformT< T2 > cast () const
ParameterTransformT< T > simplify (const ParameterSet &enabledParameters) const
Create a simplified transform given the enabled parameters.
Eigen::Index numAllModelParameters () const
Dimension of all model parameters, including pose, scaling, marker joints, and blendshape parameters for id and expressions.
Eigen::Index numJointParameters () const
Dimension of the output jointParameters vector.
Eigen::Index numBlendShapeParameters () const
Dimension of identity blendshape parameters.
Eigen::Index numFaceExpressionParameters () const
Dimension of facial expression parameters.
Eigen::Index numSkinnedLocatorParameters () const
Dimension of facial expression parameters.
Eigen::Index numSkeletonParameters () const
Dimension of skeletal model parameters, including pose parameters, scaling parameters, locator joint parameters etc.
bool isApprox (const ParameterTransformT< T > &parameterTransform) const
Static Public Member Functions
static ParameterTransformT< T > empty (size_t nJointParameters)
Return a ParameterTransform object with no model parameters.
static ParameterTransformT< T > identity (momentum::span< const std::string > jointNames)
Return a ParameterTransform object where the model parameters are identical to the joint parameters.
Public Attributes
std::vector< std::string > name
The list of model parameter names.
SparseRowMatrix< T > transform
The sparse mapping matrix that maps model parameters to joint parameters.
Eigen::VectorX< T > offsets
VectorX< bool > activeJointParams
The list of joint parameters that are actually active and influenced from the transform.
ParameterSets parameterSets
Convenience grouping of model parameters.
PoseConstraints poseConstraints
A set of predefined poses.
VectorXi blendShapeParameters
The indices of the parameters that influence blend shapes; blendShapeParameters(0) is the parameter that controls the 0th blend shape, etc.
VectorXi faceExpressionParameters
The indices of the parameters that influence face expressions; faceExpressionParameters(0) is the parameter that controls the 0th face expression parameter, etc.
VectorXi skinnedLocatorParameters
Parameters that control the rest-space positions of the skinned locators.
Detailed Description
template<typename T>
struct momentum::ParameterTransformT< T >
A parameter transform is an abstraction of the joint parameters that maps a model_parameter vector to a joint_parameter vector.
It allows mapping a single model_parameter to multiple joints, and a single joint being influenced by multiple model_parameters joint parameters are calculated from parameters in the following way : <joint_parameters> = <transform> * <model_parameters> + <offsets>
Definition at line 40 of file parameter_transform.h.
Member Function Documentation
apply() [1/2]
template<typename T > JointParametersT< T > momentum::ParameterTransformT< T >::apply (const CharacterParametersT< T > & parameters) const
Map model parameters to joint parameters using a linear transformation.
Definition at line 127 of file parameter_transform.cpp.
apply() [2/2]
template<typename T > JointParametersT< T > momentum::ParameterTransformT< T >::apply (const ModelParametersT< T > & parameters) const
Map model parameters to joint parameters using a linear transformation.
Definition at line 110 of file parameter_transform.cpp.
References MT_CHECK, and MT_PROFILE_FUNCTION.
Referenced by momentum::CharacterT< T >::bake(), momentum::d_modelParams_d_inputs(), momentum::TrustRegionQRT< T >::doIteration(), momentum::saveMotion(), momentum::saveUsdCharacterWithMotion(), and momentum::CharacterT< T >::splitParameters().
bindPose()
template<typename T > JointParametersT< T > momentum::ParameterTransformT< T >::bindPose () const
Return bind pose joint parameters (same as the rest pose here).
Definition at line 155 of file parameter_transform.cpp.
References momentum::EigenStrongType< JointParametersT, ::Eigen::VectorX< T > >::Zero().
Referenced by momentum::CharacterT< T >::initInverseBindPose(), momentum::loadLocatorsFromBuffer(), momentum::CharacterT< T >::remapLocators(), momentum::CharacterT< T >::remapParameterLimits(), and momentum::CharacterT< T >::remapSkinnedLocators().
cast()
template<typename T > template<typename T2 > template ParameterTransformT< double > momentum::ParameterTransformT< T >::cast () const
Definition at line 489 of file parameter_transform.cpp.
References momentum::ParameterTransformT< T >::activeJointParams, momentum::ParameterTransformT< T >::blendShapeParameters, momentum::ParameterTransformT< T >::faceExpressionParameters, momentum::ParameterTransformT< T >::name, name, momentum::ParameterTransformT< T >::offsets, momentum::ParameterTransformT< T >::parameterSets, momentum::ParameterTransformT< T >::poseConstraints, momentum::ParameterTransformT< T >::skinnedLocatorParameters, and momentum::ParameterTransformT< T >::transform.
computeActiveJointParams()
template<typename T > VectorX< bool > momentum::ParameterTransformT< T >::computeActiveJointParams (const ParameterSet & ps = allParams()) const
Compute activeJointParams based on the transform and the input ParameterSet.
Definition at line 96 of file parameter_transform.cpp.
empty()
template<typename T > ParameterTransformT< T > momentum::ParameterTransformT< T >::empty (size_t nJointParameters) static
Return a ParameterTransform object with no model parameters.
The model can still perform FK with JointParameters, but it does not have any degrees of freedom for IK.
Definition at line 66 of file parameter_transform.cpp.
References momentum::ParameterTransformT< T >::activeJointParams, momentum::ParameterTransformT< T >::name, momentum::ParameterTransformT< T >::offsets, and momentum::ParameterTransformT< T >::transform.
getBlendShapeParameters()
template<typename T > ParameterSet momentum::ParameterTransformT< T >::getBlendShapeParameters () const
Get a list of blend shape parameters.
Definition at line 504 of file parameter_transform.cpp.
Referenced by momentum::CharacterT< T >::bake(), momentum::CharacterT< T >::bakeBlendShape(), momentum::calibrateModel(), and momentum::HeightErrorFunctionT< T >::HeightErrorFunctionT().
getFaceExpressionParameters()
template<typename T > ParameterSet momentum::ParameterTransformT< T >::getFaceExpressionParameters () const
Get a list of face expression parameters.
Definition at line 530 of file parameter_transform.cpp.
Referenced by momentum::HeightErrorFunctionT< T >::HeightErrorFunctionT().
getParameterIdByName()
template<typename T > size_t momentum::ParameterTransformT< T >::getParameterIdByName (const std::string & nm) const
Return the index of a model parameter from its name.
Definition at line 43 of file parameter_transform.cpp.
References momentum::kInvalidIndex, and name.
Referenced by momentum::calibrateModel(), momentum::parameterSetsFromJson(), momentum::poseConstraintsFromJson(), and momentum::PoseTransformSolverT< T >::PoseTransformSolverT().
getParameterSet()
template<typename T > ParameterSet momentum::ParameterTransformT< T >::getParameterSet (const std::string & parameterSetName, bool allowMissing = false) const
Get a parameter set, if allowMissing is set then it will return an empty parameter set if no such parameterset is found in the file.
Definition at line 54 of file parameter_transform.cpp.
References MT_THROW_IF.
Referenced by momentum::calibrateModel().
getPoseParameters()
template<typename T > ParameterSet momentum::ParameterTransformT< T >::getPoseParameters () const
Return all parameters used for posing the body (excludes scaling parameters, blend shape parameters, or any parameters used for physics).
Definition at line 219 of file parameter_transform.cpp.
Referenced by momentum::trackSequence().
getRigidParameters()
template<typename T > ParameterSet momentum::ParameterTransformT< T >::getRigidParameters () const
Get a list of root parameters (with prefix "root_")
Definition at line 175 of file parameter_transform.cpp.
References name.
getScalingParameters()
template<typename T > ParameterSet momentum::ParameterTransformT< T >::getScalingParameters () const
Get a list of scaling parameters (with prefix "scale_").
Definition at line 161 of file parameter_transform.cpp.
References name.
Referenced by momentum::applyModelParameterScales(), momentum::CharacterT< T >::bake(), momentum::calibrateModel(), momentum::HeightErrorFunctionT< T >::HeightErrorFunctionT(), momentum::refineMotion(), and momentum::saveMotion().
getSkinnedLocatorParameters()
template<typename T > ParameterSet momentum::ParameterTransformT< T >::getSkinnedLocatorParameters () const
Get a list of skinned locator parameters.
Definition at line 516 of file parameter_transform.cpp.
identity()
template<typename T > ParameterTransformT< T > momentum::ParameterTransformT< T >::identity (momentum::span< const std::string > jointNames) static
Return a ParameterTransform object where the model parameters are identical to the joint parameters.
Definition at line 76 of file parameter_transform.cpp.
isApprox()
template<typename T > bool momentum::ParameterTransformT< T >::isApprox (const ParameterTransformT< T > & parameterTransform) const
Definition at line 542 of file parameter_transform.cpp.
References momentum::ParameterTransformT< T >::activeJointParams, momentum::ParameterTransformT< T >::blendShapeParameters, momentum::ParameterTransformT< T >::faceExpressionParameters, momentum::ParameterTransformT< T >::isApprox(), momentum::ParameterTransformT< T >::name, name, momentum::ParameterTransformT< T >::offsets, momentum::ParameterTransformT< T >::parameterSets, parameterTransform, momentum::ParameterTransformT< T >::poseConstraints, momentum::ParameterTransformT< T >::skinnedLocatorParameters, and momentum::ParameterTransformT< T >::transform.
Referenced by momentum::ParameterTransformT< T >::isApprox().
numAllModelParameters()
template<typename T > Eigen::Index momentum::ParameterTransformT< T >::numAllModelParameters () const inline
Dimension of all model parameters, including pose, scaling, marker joints, and blendshape parameters for id and expressions.
Definition at line 135 of file parameter_transform.h.
References momentum::ParameterTransformT< T >::transform.
Referenced by momentum::CharacterT< float >::activeJointsToParameters(), momentum::applyModelParameterScales(), momentum::CharacterT< T >::bindPose(), momentum::calibrateLocators(), momentum::calibrateModel(), momentum::computeSubsetParameterIndices(), momentum::d_modelParams_d_inputs(), momentum::FullyDifferentiableOrientationErrorFunctionT< T >::getGradient(), momentum::FullyDifferentiablePositionErrorFunctionT< T >::getGradient(), momentum::getLocatorError(), momentum::loadCharacterWithIdentity(), momentum::loadCharacterWithMotionModelParameterScales(), momentum::mapMotionToCharacter(), momentum::ModelParametersErrorFunctionT< T >::ModelParametersErrorFunctionT(), momentum::ParameterTransformT< T >::numSkeletonParameters(), momentum::PoseTransformSolverT< T >::PoseTransformSolverT(), momentum::refineMotion(), momentum::CharacterT< T >::remapLocators(), momentum::CharacterT< T >::remapParameterLimits(), momentum::CharacterT< T >::remapSkinnedLocators(), momentum::CharacterT< T >::remapSkinWeights(), momentum::saveMmo(), momentum::saveMmo(), momentum::trackPosesForFrames(), and momentum::trackSequence().
numBlendShapeParameters()
template<typename T > Eigen::Index momentum::ParameterTransformT< T >::numBlendShapeParameters () const
Dimension of identity blendshape parameters.
Definition at line 203 of file parameter_transform.cpp.
Referenced by momentum::ParameterTransformT< T >::numSkeletonParameters().
numFaceExpressionParameters()
template<typename T > Eigen::Index momentum::ParameterTransformT< T >::numFaceExpressionParameters () const
Dimension of facial expression parameters.
Definition at line 208 of file parameter_transform.cpp.
Referenced by momentum::ParameterTransformT< T >::numSkeletonParameters().
numJointParameters()
template<typename T > Eigen::Index momentum::ParameterTransformT< T >::numJointParameters () const inline
Dimension of the output jointParameters vector.
Definition at line 140 of file parameter_transform.h.
References momentum::ParameterTransformT< T >::transform.
numSkeletonParameters()
template<typename T > Eigen::Index momentum::ParameterTransformT< T >::numSkeletonParameters () const inline
Dimension of skeletal model parameters, including pose parameters, scaling parameters, locator joint parameters etc.
basically everything but blendshapes (ids and expressions).
Definition at line 156 of file parameter_transform.h.
References momentum::ParameterTransformT< T >::numAllModelParameters(), momentum::ParameterTransformT< T >::numBlendShapeParameters(), momentum::ParameterTransformT< T >::numFaceExpressionParameters(), and momentum::ParameterTransformT< T >::numSkinnedLocatorParameters().
numSkinnedLocatorParameters()
template<typename T > Eigen::Index momentum::ParameterTransformT< T >::numSkinnedLocatorParameters () const
Dimension of facial expression parameters.
Definition at line 213 of file parameter_transform.cpp.
Referenced by momentum::ParameterTransformT< T >::numSkeletonParameters().
simplify()
template<typename T > ParameterTransformT< T > momentum::ParameterTransformT< T >::simplify (const ParameterSet & enabledParameters) const
Create a simplified transform given the enabled parameters.
Definition at line 225 of file parameter_transform.cpp.
References momentum::subsetParameterTransform().
Referenced by momentum::applyModelParameterScales().
zero()
template<typename T > JointParametersT< T > momentum::ParameterTransformT< T >::zero () const
Return rest pose joint parameters.
Definition at line 148 of file parameter_transform.cpp.
Member Data Documentation
activeJointParams
template<typename T > VectorX<bool> momentum::ParameterTransformT< T >::activeJointParams
The list of joint parameters that are actually active and influenced from the transform.
Definition at line 51 of file parameter_transform.h.
Referenced by momentum::ParameterTransformT< T >::cast(), momentum::ParameterTransformT< T >::empty(), momentum::ParameterTransformT< T >::isApprox(), momentum::parameterTransformFromJson(), momentum::parseParameterTransform(), and momentum::writeParameterTransform().
blendShapeParameters
template<typename T > VectorXi momentum::ParameterTransformT< T >::blendShapeParameters
The indices of the parameters that influence blend shapes; blendShapeParameters(0) is the parameter that controls the 0th blend shape, etc.
Definition at line 61 of file parameter_transform.h.
Referenced by momentum::ParameterTransformT< T >::cast(), momentum::ParameterTransformT< T >::isApprox(), momentum::mapParameterTransformJoints(), and momentum::parameterTransformToJson().
faceExpressionParameters
template<typename T > VectorXi momentum::ParameterTransformT< T >::faceExpressionParameters
The indices of the parameters that influence face expressions; faceExpressionParameters(0) is the parameter that controls the 0th face expression parameter, etc.
Definition at line 65 of file parameter_transform.h.
Referenced by momentum::ParameterTransformT< T >::cast(), momentum::ParameterTransformT< T >::isApprox(), momentum::mapParameterTransformJoints(), and momentum::parameterTransformToJson().
name
template<typename T > std::vector<std::string> momentum::ParameterTransformT< T >::name
The list of model parameter names.
Definition at line 42 of file parameter_transform.h.
Referenced by momentum::applyModelParameterScales(), momentum::ParameterTransformT< T >::cast(), momentum::ParameterTransformT< T >::empty(), momentum::ParameterTransformT< T >::isApprox(), momentum::mapMotionToCharacter(), momentum::mapParameterTransformJoints(), momentum::parameterSetsToJson(), momentum::parameterTransformToJson(), momentum::poseConstraintsToJson(), momentum::saveCharacter(), momentum::saveMmo(), momentum::saveMotion(), momentum::writeModelDefinition(), momentum::writeParameterLimits(), and momentum::writeParameterTransform().
offsets
template<typename T > Eigen::VectorX<T> momentum::ParameterTransformT< T >::offsets
Deprecated:
Constant offset factor for each joint.
Definition at line 48 of file parameter_transform.h.
Referenced by momentum::ParameterTransformT< T >::cast(), momentum::ParameterTransformT< T >::empty(), momentum::ParameterTransformT< T >::isApprox(), momentum::mapParameterTransformJoints(), momentum::replaceSkeletonHierarchy(), momentum::CharacterT< float >::withFaceExpressionBlendShape(), and momentum::writeParameterTransform().
parameterSets
template<typename T > ParameterSets momentum::ParameterTransformT< T >::parameterSets
Convenience grouping of model parameters.
Definition at line 54 of file parameter_transform.h.
Referenced by momentum::calibrateLocators(), momentum::ParameterTransformT< T >::cast(), momentum::ParameterTransformT< T >::isApprox(), momentum::loadParameters(), momentum::mapParameterTransformJoints(), momentum::parameterSetsToJson(), momentum::refineMotion(), and momentum::writeModelDefinition().
poseConstraints
template<typename T > PoseConstraints momentum::ParameterTransformT< T >::poseConstraints
A set of predefined poses.
Definition at line 57 of file parameter_transform.h.
Referenced by momentum::addSequenceFrameConstraints(), momentum::ParameterTransformT< T >::cast(), momentum::ParameterTransformT< T >::isApprox(), momentum::loadParameters(), momentum::mapParameterTransformJoints(), momentum::poseConstraintsToJson(), and momentum::writeModelDefinition().
skinnedLocatorParameters
template<typename T > VectorXi momentum::ParameterTransformT< T >::skinnedLocatorParameters
Parameters that control the rest-space positions of the skinned locators.
This array will be either empty or have the same size as the number of skinned locators. Each entry maps from a skinned locator index to the first of the three (x,y,z) parameters that control its position. Skinned locators that aren't controlled by the paramete transform will have skinnedLocatorParameters[i] = -1.
Definition at line 73 of file parameter_transform.h.
Referenced by momentum::ParameterTransformT< T >::cast(), momentum::ParameterTransformT< T >::isApprox(), and momentum::mapParameterTransformJoints().
transform
template<typename T > SparseRowMatrix<T> momentum::ParameterTransformT< T >::transform
The sparse mapping matrix that maps model parameters to joint parameters.
Definition at line 45 of file parameter_transform.h.
Referenced by momentum::CharacterT< float >::activeJointsToParameters(), momentum::ParameterTransformT< T >::cast(), momentum::ParameterTransformT< T >::empty(), momentum::gradient_jointParams_to_modelParams(), momentum::gradient_jointParams_to_modelParams(), momentum::ParameterTransformT< T >::isApprox(), momentum::jacobian_jointParams_to_modelParams(), momentum::jacobian_jointParams_to_modelParams(), momentum::jacobian_jointParams_to_modelParams(), momentum::jacobian_jointParams_to_modelParams(), momentum::jacobian_jointParams_to_modelParams(), momentum::mapParameterTransformJoints(), momentum::ParameterTransformT< T >::numAllModelParameters(), momentum::ParameterTransformT< T >::numJointParameters(), momentum::CharacterT< T >::parametersToActiveJoints(), momentum::parameterTransformToJson(), momentum::times_parameterTransform_times_v(), and momentum::writeParameterTransform().
The documentation for this struct was generated from the following files:
character/fwd.h
character/parameter_transform.h
character/parameter_transform.cpp