Momentum: momentum::CollisionOverlapResultT< T > Struct Template Reference
momentum::CollisionOverlapResultT< T > Struct Template Reference
Narrow-phase collision information for a pair of primitives.
#include <collision_geometry_state.h>
Public Attributes
T distance = T(0)
Distance between the primitive center features used by the narrow phase.
Vector2< T > closestPoints = Vector2<T>::Zero()
Parametric closest-point positions. Capsule entries use [0, 1]; ellipsoid entries use 0.
T overlap = T(0)
Amount of overlap, positive when colliding.
Vector3< T > positionA = Vector3<T>::Zero()
Center feature position for the first primitive.
Vector3< T > positionB = Vector3<T>::Zero()
Center feature position for the second primitive.
T radiusA = T(0)
Effective radius of the first primitive along the contact direction.
T radiusB = T(0)
Effective radius of the second primitive along the contact direction.
Detailed Description
template<typename T>
struct momentum::CollisionOverlapResultT< T >
Narrow-phase collision information for a pair of primitives.
Definition at line 66 of file collision_geometry_state.h.
Member Data Documentation
closestPoints
template<typename T > Vector2<T> momentum::CollisionOverlapResultT< T >::closestPoints = Vector2<T>::Zero()
Parametric closest-point positions. Capsule entries use [0, 1]; ellipsoid entries use 0.
Definition at line 71 of file collision_geometry_state.h.
Referenced by momentum::overlaps().
distance
template<typename T > T momentum::CollisionOverlapResultT< T >::distance = T(0)
Distance between the primitive center features used by the narrow phase.
Definition at line 68 of file collision_geometry_state.h.
Referenced by momentum::overlaps().
overlap
template<typename T > T momentum::CollisionOverlapResultT< T >::overlap = T(0)
Amount of overlap, positive when colliding.
Definition at line 74 of file collision_geometry_state.h.
Referenced by momentum::overlaps().
positionA
template<typename T > Vector3<T> momentum::CollisionOverlapResultT< T >::positionA = Vector3<T>::Zero()
Center feature position for the first primitive.
Definition at line 77 of file collision_geometry_state.h.
Referenced by momentum::overlaps().
positionB
template<typename T > Vector3<T> momentum::CollisionOverlapResultT< T >::positionB = Vector3<T>::Zero()
Center feature position for the second primitive.
Definition at line 80 of file collision_geometry_state.h.
Referenced by momentum::overlaps().
radiusA
template<typename T > T momentum::CollisionOverlapResultT< T >::radiusA = T(0)
Effective radius of the first primitive along the contact direction.
Definition at line 83 of file collision_geometry_state.h.
Referenced by momentum::overlaps().
radiusB
template<typename T > T momentum::CollisionOverlapResultT< T >::radiusB = T(0)
Effective radius of the second primitive along the contact direction.
Definition at line 86 of file collision_geometry_state.h.
Referenced by momentum::overlaps().
The documentation for this struct was generated from the following file:
character/collision_geometry_state.h